apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: eda-demo-24-cluster
spec:
  kafka:
    version: 2.4.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.4"
    # Add next for using kafka with persistence
    storage:
      type: ephemeral
    #  type: jbod
    #  volumes:
    #  - id: 0
    #    type: persistent-claim
    #    size: 20Gi
    #   deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
    #  type: persistent-claim
    #  size: 20Gi
    # deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}