# oc create secret generic additional-scrape-configs --from-file=prometheus-additional.yaml
- job_name: 'MirrorMaker2'
  static_configs:
   - targets:
     - mm2ocp.eda-strimzi-kafka24.svc.cluster.local:9400
